server:
  port: "8080"
spring:
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
  datasource:
    url: "jdbc:postgresql://localhost:5432/catsgram"
    username: "dbuser"
    password: "12345"
    driver-class-name: "org.postgresql.Driver"